### PR TITLE
Report error messages for 4xx responses

### LINKED ISSUE #41: Error messages from 4xx responses are not included in exceptions
**Describe the bug**
When a 4xx error occurs, for example because an invalid classifier name has been used, the `WaivesApiException` that is thrown by the `WaivesClient` does not include the error message returned by the Waives service.

**To Reproduce**
Run the following code:
```
           const string filepath = @"F:\demo\classification-mortgages\test\single\Notice of Default.pdf";
            var client = new WaivesClient();
            await client.Login(ClientId, ClientSecret);

            Waives.Http.Document document = null;
            try
            {
                document = await client.CreateDocument(File.OpenRead(filepath));
                await document.Classify("non-existent-classifier");
            }
            catch (WaivesApiException ex)
            {
                Console.WriteLine($"Error: {ex.Message}");
            }
            finally
            {
                if (document != null)
                {
                    await document.Delete();
                }
            }

            Console.ReadLine();
```

**Expected behaviour**
The `WaivesApiException` that is thrown includes the error message returned by the service. In the example above this would be `The classifier called 'non-existent-classifier' does not exist. Call /classifiers/non-existent-classifier to create a classifier and then add training samples.`

**System details(please complete the following information):**
 - OS: Windows 10
 - CLR and version: Cre CLR 2.1.2
 - SDK version: 0.8.2

**Additional context**
None

### PR DESCRIPTION
**Pull request by alastairs**
Fixes #41.

### Root cause

While investigating the missing error messages reported in #41, I found that a bunch of inappropriate response status codes (all the 4xx responses, for example) were incorrectly causing the request to be retried. There's been a bit of reshuffling of concerns to resolve this issue, but thankfully resolving these has meant that the original issue essentially evaporated.

### Proposed resolution

We now have the following implementations of `IHttpRequestSender`, from the bottom of the object graph to the top:

* **`RequestSender`**: wraps an `HttpClient`, setting default values on it, such as user-agent string and OAuth access token.
* **`ReliableRequestSender`**: wraps the `RequestSender` and an `ILogger` to retry failed requests that meet the set policy of exponential retries. 
* **`FailedRequestHandlingRequestSender`**: wraps the `ReliableRequestSender` and throws a `WaivesApiException` for any request which failed the retry policy.
* **`TimeoutHandlingRequestSender`**: this was the `ExceptionHandlingRequestSender`, but it now only handles exceptions related to timeouts, so has been renamed. This wraps the `FailedRequestHandlingRequestSender`. 
* **`LoggingRequestSender`**: wraps the `TimeoutHandlingRequestSender` to log the HTTP request/response pair and request duration. 

I have also updated the File Sorter and Blob Storage sample apps to surface errors thrown during processing: neither implemented an `OnDocumentError()` handler for their pipelines. Additionally, the File Sorter now implements its specified error behaviour of moving failed files to the failures' directory and writing out the error message with it in a log file; and the Blob Storage processor now waits for the pipeline to complete before exiting.

### CODE REVIEW

File: samples/BlobStorageProcessor/Program.cs [hunk 1]
```diff
@@ -68,9 +68,17 @@ public static async Task Main(string[] args)
                 ClientSecret = "clientSecret"
             });
 
+            var completion = new TaskCompletionSource<bool>();
```
Comment (phildrip) [inline samples/BlobStorageProcessor/Program.cs]: :+1:
