### PR TITLE
Fix #55, "unhandled exceptions stall pipeline"

### LINKED ISSUE #55: Unhandled exceptions in OnDocumentError cause pipeline to stall and documents be left behind
**Describe the bug**
If the user writes code in the `OnDocumentError()` handler, and that code throws an exception which is not caught in their code then the pipeline stalls and documents are left undeleted in the service.

**To Reproduce**
Run the following code (updating the document source file path to a folder containing a few documents)

```
var pipeline = await WaivesApi.CreatePipeline(new WaivesOptions
{
     ClientId = ClientId,
     ClientSecret = ClientSecret,
});

var fileSystemDocumentSource = FileSystem.ReadFrom(@"F:\demo\classification-mortgages\test");

pipeline.WithDocumentsFrom(fileSystemDocumentSource)
        .ClassifyWith("mortgages")
        .Then(d =>
        {
             throw new Exception("ThenException");
         })
         .OnDocumentError(d =>
         {
              throw new Exception("OnDocumentErrorException");
          })

          pipeline.Start();
```

**Expected behaviour**
~~The user-thrown exception is caught by the SDK and logged as an error, but otherwise processing continues as normal.~~
The document is deleted, and the pipeline halts execution. It's left to the consuming application to provide a resilient error handler operation.

**System details(please complete the following information):**
 - SDK version: commit 41f244e

### PR DESCRIPTION
**Pull request by phildrip**
This PR:

* Ensures that user-supplied error handlers no longer stall the pipeline
* If any error handlers do throw, any document created in waives is also deleted
* Ensures that `Pipeline.RunAsync` also throws, since there's nothing else we can do.

Fixes #55.

### CODE REVIEW

File: src/Waives.Pipelines/DocumentProcessor.cs [hunk 1]
```diff
@@ -9,28 +9,39 @@ internal class DocumentProcessor : IDocumentProcessor
     {
         private readonly Func<Document, Task<WaivesDocument>> _docCreator;
         private readonly IEnumerable<Func<WaivesDocument, Task<WaivesDocument>>> _docActions;
+        private readonly Func<WaivesDocument, Task> _docDeleter;
```
Comment (alastairs) [inline src/Waives.Pipelines/DocumentProcessor.cs]: This file needs flagging for #84—`doc` vs. ` document`.

File: src/Waives.Pipelines/DocumentProcessor.cs [hunk 2]
```diff
@@ -9,28 +9,39 @@ internal class DocumentProcessor : IDocumentProcessor
...
         {
             _docCreator = docCreator ?? throw new ArgumentNullException(nameof(docCreator));
             _docActions = docActions ?? throw new ArgumentNullException(nameof(docActions));
+            _docDeleter = docDeleter ?? throw new ArgumentNullException(nameof(docDeleter));
             _onDocumentException = onDocumentException ?? throw new ArgumentNullException(nameof(onDocumentException));
         }
 
         public async Task RunAsync(Document document)
         {
+            WaivesDocument waivesDocument = null;
```
Comment (alastairs) [inline src/Waives.Pipelines/DocumentProcessor.cs]: I think `WaivesDocument` has an `IHttpDocument` so could be made `IDisposable` perhaps?

File: src/Waives.Pipelines/Pipeline.cs [hunk 3]
```diff
@@ -247,27 +231,49 @@ void OnPipelineError(Exception e)
...
+                catch (Exception e)
+                {
+                    _logger.Error(e, "An error occurred when calling the error handler");
+
+                    taskCompletion.TrySetException(e);
+                }
             }
 
-            _logger.Info("Pipeline started");
+            Func<Document, Task<WaivesDocument>> docCreator = async d =>
```
Comment (alastairs) [inline src/Waives.Pipelines/Pipeline.cs]: This variable needs flagging for #84.

File: src/Waives.Pipelines/Pipeline.cs [hunk 4]
```diff
@@ -247,27 +231,49 @@ void OnPipelineError(Exception e)
...
-                    _logger.Info("Started processing '{DocumentSourceId}'", d.SourceId);
+                var httpDocument = await _documentFactory
+                    .CreateDocument(d).ConfigureAwait(false);
 
-                    var httpDocument = await _documentFactory
-                        .CreateDocument(d).ConfigureAwait(false);
+                return new WaivesDocument(d, httpDocument);
+            };
+
+            Func<WaivesDocument, Task> docDeleter = async d =>
```
Comment (alastairs) [inline src/Waives.Pipelines/Pipeline.cs]: Flagging for #84.

File: src/Waives.Pipelines/Pipeline.cs [hunk 5]
```diff
@@ -276,9 +282,15 @@ void OnDocumentException(Exception exception, Document document)
                 OnPipelineError,
                 _maxConcurrency);
 
-            _docSource.Subscribe(pipelineObserver);
-
-            await taskCompletion.Task;
+            var connection = _docSource.Subscribe(pipelineObserver);
```
Comment (alastairs) [inline src/Waives.Pipelines/Pipeline.cs]: Flagging for #84. Also `Subscribe` returns an `IDisposable`, so we can use a `using` here instead of `try..finally`.

File: test/Waives.Pipelines.Tests/DocumentProcessorFacts.cs [hunk 6]
```diff
@@ -11,6 +11,7 @@ namespace Waives.Pipelines.Tests
     public class DocumentProcessorFacts
     {
         private readonly Func<Document, Task<WaivesDocument>> _docCreator;
+        private readonly Func<WaivesDocument, Task> _docDeleter;
```
Comment (alastairs) [inline test/Waives.Pipelines.Tests/DocumentProcessorFacts.cs]: Flagging for #84.

File: test/Waives.Pipelines.Tests/DocumentProcessorFacts.cs [hunk 7]
```diff
@@ -71,13 +75,58 @@ public async Task Fires_error_handler_on_error()
...
+                _docDeleter,
                 (exception, document) => { errorHandlerRun = true; });
 
             await sut.RunAsync(_testDocument);
 
             Assert.True(errorHandlerRun);
         }
 
+        [Fact]
+        public async Task Deletes_document_after_error()
```
Comment (alastairs) [inline test/Waives.Pipelines.Tests/DocumentProcessorFacts.cs]: Flagging this test for #84.

File: test/Waives.Pipelines.Tests/DocumentProcessorFacts.cs [hunk 8]
```diff
@@ -71,13 +75,58 @@ public async Task Fires_error_handler_on_error()
...
+                fakeDocActions.Select<FakeDocAction, Func<WaivesDocument, Task<WaivesDocument>>>(f => f.ThrowError),
+                docDeleter,
+                _onDocumentException);
+            await sut.RunAsync(_testDocument);
+
+            Assert.True(docDeleted);
+        }
+
+        [Fact]
+        public async Task Deletes_document_after_error_in_error_handler()
```
Comment (alastairs) [inline test/Waives.Pipelines.Tests/DocumentProcessorFacts.cs]: Flagging this test for #84.
